version: '3'
services:
  nextjs:
    build: ./
    image: nextjs-prisma:1.0.0
    ports:
      - "3000:3000"
    environment:
      - HOSTNAME=0.0.0.0
  mysqldb:
    build: ./mysql/
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: SampleDB
      TZ: 'Asia/Tokyo'
      BIND-ADDRESS: 0.0.0.0
    volumes:
      - ./mysql/conf.d/:/etc/mysql/conf.d/
      - ./mysql/initdb.d/:/docker-entrypoint-initdb.d
      
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_DB_HOST: mysqldb
      ADMINER_DEFAULT_DB_NAME: SampleDB