version: 0.2

env:
  secrets-manager:
    SONARQUBE_HOST: "arn:aws:secretsmanager:ap-northeast-1:151268123722:secret:sonarqube-HNjd2g:SONARQUBE_HOST::"
    SONARQUBE_SECRET: "arn:aws:secretsmanager:ap-northeast-1:151268123722:secret:sonarqube-HNjd2g:SONARQUBE_SECRET::"

phases:
  install:
    commands:
      - SONARQUBE_HOST=${SONARQUBE_HOST}
      - SONARQUBE_SECRET=${SONARQUBE_SECRET}
      - n 16.3.0
      - node -v
      - yarn -v 
      - printenv

  pre_build: 
    commands:
      - echo yarn install
      - yarn install

  build:
    # image: aws/codebuild/amazonlinux2-x86_64-standard:4.0
    commands:
      - echo yarn sonar
      - yarn sonar
