version: 0.2

env:
  variables:
    AWS_REGION_NAME: ap-northeast-1


phases:
  install:
    commands:
      - n 16.3.0
      - node -v
      - yarn -v 
      - printenv

  pre_build: 
    commands:
      - echo yarn install
      - yarn install

  build:
    # image: aws/codebuild/amazonlinux2-x86_64-standard:4.0
    commands:
      - echo yarn sonar
      - yarn sonar
