version: 1
Resources:
- TargetService:
    Type: AWS::ECS::Service
    Properties:
        TaskDefinition: "<TASK_DEFINITION>"
        LoadBalancerInfo: 
            ContainerName: "nextjs"
            ContainerPort: 3000
